spring:
  datasource:
    url: jdbc:postgresql://piworm.local:5432/timebeam
    username: timebeam
    password: timebeam
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 600000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    org.springframework: DEBUG
    com.zaxxer.hikari: INFO
    org.hibernate: DEBUG
    com.sparkage.timebeam: TRACE
    org.springframework.web.socket: DEBUG

apns:
  enabled: false